export type ElectronAppLocale = "ko" | "en";

const ko = {
  trayShowApp: "Language Miner 열기",
  trayCaptureRunning: "Life Mining 백그라운드 수집 실행 중",
  trayQuit: "완전히 종료",
  readerDocumentTitle: "리더에서 열 문서 선택",
  readerDocumentFilter: "리더 문서",
  localVideoTitle: "Video Reader에서 열 로컬 영상 선택",
  localVideoFilter: "영상 파일",
  localVideoFolderTitle: "영상 폴더 추가",
  cardSyncFolderTitle: "Language Miner 카드 동기화 폴더 선택",
  backupSaveTitle: "Language Miner 전체 백업 저장",
  backupSaveButton: "백업 저장",
  backupOpenTitle: "Language Miner 백업 열기",
  backupOpenButton: "백업 확인",
  backupFilter: "Language Miner 백업",
  playZonePackTitle: "PlayZone 팩 파일 선택",
  playZonePackFilter: "PlayZone 팩 파일",
  playZoneFolderTitle: "PlayZone 게임 라이브러리 폴더 선택",
  webReaderLoginTitle: "웹 리더 로그인",
  externalOcrTitle: "외부 OCR 캡처",
  externalOcrAppName: "외부 OCR",
  runtimeTrayAvailable: "시스템 트레이 백그라운드 수집을 사용할 수 있습니다.",
  runtimeTrayDevelopment:
    "시스템 트레이를 사용할 수 있습니다. Windows 시작 시 실행 설정은 설치판에서 적용됩니다.",
  runtimeDesktopOcrShortcutUnavailable:
    "다른 앱이 Ctrl+Q를 사용 중이어서 외부 OCR 단축키를 등록하지 못했습니다. 해당 앱의 단축키를 바꾼 뒤 Language Miner를 다시 실행하세요.",
  runtimeStartupPackagedOnly: "Windows 시작 시 실행은 설치판에서만 켤 수 있습니다.",
  runtimeStartupEnabled: "Windows를 시작할 때 Language Miner가 함께 실행됩니다.",
  runtimeStartupDisabled: "Windows를 시작할 때 Language Miner가 자동으로 실행되지 않습니다.",
  desktopCardSelectionRequired: "카드로 만들 표현과 문장이 필요합니다.",
  inputLanguageMismatchMarker: "선택한 문장의 언어가 현재 학습 프로필과 다릅니다.",
  inputLanguageMismatch:
    "선택한 문장의 언어가 현재 학습 프로필과 다릅니다. 현재 프로필: {expected} · 감지: {detected}",
  webReaderUnavailable: "웹 리더가 열려 있지 않습니다.",
  webReaderOwnerUnavailable: "웹 리더를 표시할 앱 창을 찾지 못했습니다.",
  lifeMiningOff: "Life Mining이 꺼져 있습니다. 설정에서 켜면 수집을 시작합니다.",
  lifeMiningWaitingForPage: "웹 페이지가 열리면 Life Mining 상태를 확인합니다.",
  lifeMiningDisabledOnSignIn: "로그인 화면에서는 Life Mining을 끕니다.",
  lifeMiningAutoSelectionOn: "Life Mining 켜짐 · 자동/선택 캡처",
  lifeMiningSelectionOn: "Life Mining 켜짐 · 선택 텍스트 캡처",
  lifeMiningSiteOff: "이 사이트의 Life Mining이 꺼져 있습니다.",
  webAddressUnavailable: "웹 주소를 확인할 수 없습니다.",
  lifeMiningInjectionUnavailable: "이 페이지에서는 Life Mining을 실행할 수 없습니다.",
  webReaderClosed: "웹 리더가 닫혔습니다.",
  lifeMiningSkipped: "Life Mining 후보를 건너뛰었습니다.",
  lifeMiningDuplicateSkipped: "중복된 Life Mining 후보를 건너뛰었습니다.",
  lifeMiningCandidateSaved: "Life Mining 후보를 저장했습니다.",
  discordConversationUnavailable:
    "Discord 대화방 또는 입력창을 찾지 못했습니다. DM이나 채널 대화를 연 뒤 수집할 수 있습니다.",
  webReaderAppName: "웹 리더",
  youtubeVideoFallback: "YouTube 영상 {videoId}",
  localFileSourceName: "로컬 파일",
  playZoneBundledMissing: "설치된 앱에서 기본 PlayZone 게임 파일을 찾지 못했습니다.",
  usageBudgetLimit: "이 기기의 예상 사용량 가드에 도달했습니다.",
  usageDailyLimitExceeded:
    "오늘 누적 예상 토큰 {projected}개가 이 기기의 일일 가드 {limit}개를 초과합니다.",
  usageMonthlyLimitExceeded:
    "이번 달 누적 예상 비용 {projected}원이 이 기기의 월간 가드 {limit}원을 초과합니다.",
  backupWindowUnavailable: "백업 창을 찾지 못했습니다.",
  backupRestoreAndRollbackFailed:
    "복원과 자동 롤백에 실패했습니다. 안전 백업 {backupName}을 보존했습니다. {restoreError} / 롤백: {rollbackError}",
  backupRestoreRolledBack: "복원에 실패해 기존 데이터를 자동으로 되돌렸습니다. {error}",
  backupRequestInvalid: "백업 요청 형식이 올바르지 않습니다.",
  restoreRequestInvalid: "복원 요청 형식이 올바르지 않습니다.",
  restorePreviewMissing: "복원 미리보기를 찾지 못했습니다. 백업 파일을 다시 확인해 주세요.",
  restoreModeUnsupported: "지원하지 않는 복원 방식입니다.",
  rendererBackupMissing: "화면 설정 백업 데이터가 없습니다.",
  rendererBackupInvalid: "화면 설정 백업 항목 형식이 올바르지 않습니다.",
  unknownError: "알 수 없는 오류",
  listeningSourceAudioFailed: "리스닝 카드 원본 오디오를 만들지 못했습니다.",
  listeningEmbeddedImportedOne: "내장 자막 1개를 가져왔습니다.",
  listeningEmbeddedImported: "내장 자막 {count}개를 가져왔습니다.",
  listeningEmbeddedUnavailable:
    "텍스트 내장 자막을 가져오지 못했습니다. 필요하면 Whisper 전사를 실행해 주세요.",
  listeningCandidateUnavailable: "영상 후보를 찾지 못했습니다.",
  listeningSegmentCreatedOne: "문장 구간 1개를 만들었습니다.",
  listeningSegmentsCreated: "문장 구간 {count}개를 만들었습니다.",
  listeningWhisperFailed: "Whisper 자막을 만들지 못했습니다.",
  listeningLocalWhisperFailed: "로컬 영상의 Whisper 자막을 만들지 못했습니다.",
  translationTextMissing: "번역할 텍스트가 없습니다.",
  localVideoPlaybackFallback:
    "재생용 MP4를 준비하지 못해 원본 파일로 재생을 시도합니다.",
  cardSyncNotConfigured: "동기화 폴더를 선택해 주세요.",
  cardSyncFolderFallback: "선택한 폴더",
  cardSyncFolderMissing: "동기화 폴더 ‘{folderName}’을 찾을 수 없습니다.",
  cardSyncRemoteFound: "동기화 폴더에서 카드 파일을 찾았습니다.",
  cardSyncFolderReady: "동기화 폴더가 준비되었습니다. 아직 카드 파일은 없습니다.",
  cardSyncDisconnected: "동기화 폴더 연결을 해제했습니다.",
  cardSyncUploadedOne: "카드 1장을 동기화 폴더에 업로드했습니다.",
  cardSyncUploaded: "카드 {count}장을 동기화 폴더에 업로드했습니다.",
  cardSyncDownloadedOne: "폴더의 카드 변경 1개를 가져왔습니다.",
  cardSyncDownloaded: "폴더의 카드 변경 {count}개를 가져왔습니다.",
  cardSyncCompleted: "동기화 완료 · 업로드 {uploaded}장 · 다운로드 {downloaded}장",
  cardSyncConflictCopies: "충돌 복사본 {count}장을 만들었습니다.",
  cardSyncConflictCopyOne: "충돌 복사본 1장을 만들었습니다.",
  cardSyncFolderUnavailable: "동기화 폴더 ‘{folderName}’을 사용할 수 없습니다.",
  cardSyncRemoteMissing:
    "동기화 폴더에 카드 파일이 없습니다. 먼저 업로드하거나 동기화를 실행해 주세요.",
  cardSyncReadFailed: "동기화 카드 파일을 읽을 수 없습니다.",
  cardSyncWriteFailed: "동기화 카드 파일을 안전하게 저장할 수 없습니다.",
  listeningYouTubeTitle: "YouTube 듣기 플레이어",
  listeningYouTubePreparing: "YouTube 플레이어 준비 중…",
  listeningYouTubeError: "YouTube 플레이어 오류 {code}",
  ocrCaptureHeading: "OCR 캡처",
  ocrCaptureHint: "텍스트가 있는 영역을 드래그하세요. Esc를 누르면 취소합니다.",
  ocrCaptureReady: "Ctrl+Q 캡처 대기",
  ocrAreaTooSmall: "영역이 너무 작습니다. 다시 드래그하세요.",
  ocrProcessing: "OCR 처리 중…",
  ocrCaptureFailed: "OCR 캡처에 실패했습니다.",
  ocrDisplayUnavailable: "캡처할 화면 정보를 찾을 수 없습니다.",
  ocrScreenshotUnavailable: "스크린샷을 가져올 수 없습니다.",
  ocrWindowsOnly: "현재 OCR 기능은 Windows 내장 OCR만 지원합니다.",
  ocrComplete: "OCR 처리가 끝났습니다.",
  ocrEmpty: "인식된 텍스트가 없습니다. 아래 입력란에서 직접 작성할 수 있습니다.",
  ocrFailed: "OCR 처리에 실패했습니다. 아래 입력란에서 직접 작성할 수 있습니다.",
  ocrCapturedImageAlt: "캡처한 이미지",
  ocrClose: "닫기",
  ocrEditableHint:
    "OCR 텍스트를 수정할 수 있습니다. 단어나 표현을 드래그해 읽기 카드로 저장하세요.",
  ocrManualCreate: "선택한 표현으로 읽기 카드 만들기",
  ocrRecapture: "다시 캡처",
  ocrCreate: "읽기 카드 만들기",
  ocrSelectFirst: "먼저 OCR 텍스트에서 단어나 표현을 드래그하세요.",
  ocrCreatingCard: "읽기 카드를 만드는 중…",
  ocrCardSaved: "읽기 카드를 저장했습니다.",
  ocrCardSaveUnknown: "카드 저장 결과를 확인할 수 없습니다.",
  ocrCardCreateFailed: "카드를 만들지 못했습니다.",
  ocrMismatchTitle: "문장 언어 확인",
  ocrProfileForcePrompt: "현재 프로필에 그대로 저장할까요?",
  ocrMismatchCancel: "취소",
  ocrMismatchSaveAnyway: "그래도 저장",
  ocrMismatchSaved: "언어 불일치를 확인하고 카드를 저장했습니다."
} as const;

export type ElectronTextKey = keyof typeof ko;

const en: Record<ElectronTextKey, string> = {
  trayShowApp: "Open Language Miner",
  trayCaptureRunning: "Life Mining background capture is running",
  trayQuit: "Quit completely",
  readerDocumentTitle: "Select a document for Reader",
  readerDocumentFilter: "Reader documents",
  localVideoTitle: "Select a local video for Video Reader",
  localVideoFilter: "Video files",
  localVideoFolderTitle: "Add a video folder",
  cardSyncFolderTitle: "Choose a Language Miner card sync folder",
  backupSaveTitle: "Save a complete Language Miner backup",
  backupSaveButton: "Save backup",
  backupOpenTitle: "Open a Language Miner backup",
  backupOpenButton: "Review backup",
  backupFilter: "Language Miner backup",
  playZonePackTitle: "Select a PlayZone pack file",
  playZonePackFilter: "PlayZone pack files",
  playZoneFolderTitle: "Select a PlayZone game library folder",
  webReaderLoginTitle: "Web Reader sign-in",
  externalOcrTitle: "External OCR capture",
  externalOcrAppName: "External OCR",
  runtimeTrayAvailable: "System tray background capture is available.",
  runtimeTrayDevelopment:
    "The system tray is available. Start-with-Windows settings are applied in the installed app.",
  runtimeDesktopOcrShortcutUnavailable:
    "The external OCR shortcut could not be registered because another app is using Ctrl+Q. Change the conflicting shortcut, then restart Language Miner.",
  runtimeStartupPackagedOnly: "Start with Windows can only be enabled in the installed app.",
  runtimeStartupEnabled: "Language Miner will start with Windows.",
  runtimeStartupDisabled: "Language Miner will not start automatically with Windows.",
  desktopCardSelectionRequired: "An expression and sentence are required to create a card.",
  inputLanguageMismatchMarker: "The selected sentence does not match the current learning profile.",
  inputLanguageMismatch:
    "The selected sentence does not match the current learning profile. Current profile: {expected} · detected: {detected}",
  webReaderUnavailable: "Web Reader is not open.",
  webReaderOwnerUnavailable: "The app window for Web Reader is unavailable.",
  lifeMiningOff: "Life Mining is off. Enable it in Settings to begin capture.",
  lifeMiningWaitingForPage: "Life Mining status will appear after a web page opens.",
  lifeMiningDisabledOnSignIn: "Life Mining is disabled on sign-in pages.",
  lifeMiningAutoSelectionOn: "Life Mining on · automatic and selection capture",
  lifeMiningSelectionOn: "Life Mining on · selected-text capture",
  lifeMiningSiteOff: "Life Mining is off for this site.",
  webAddressUnavailable: "The web address could not be read.",
  lifeMiningInjectionUnavailable: "Life Mining cannot run on this page.",
  webReaderClosed: "Web Reader was closed.",
  lifeMiningSkipped: "The Life Mining candidate was skipped.",
  lifeMiningDuplicateSkipped: "A duplicate Life Mining candidate was skipped.",
  lifeMiningCandidateSaved: "The Life Mining candidate was saved.",
  discordConversationUnavailable:
    "No Discord conversation or message box was found. Open a DM or channel conversation to capture it.",
  webReaderAppName: "Web Reader",
  youtubeVideoFallback: "YouTube video {videoId}",
  localFileSourceName: "Local file",
  playZoneBundledMissing: "A bundled PlayZone game is missing from this installation.",
  usageBudgetLimit: "This device's estimated usage guard has been reached.",
  usageDailyLimitExceeded:
    "Today's projected total of {projected} tokens exceeds this device's daily guard of {limit} tokens.",
  usageMonthlyLimitExceeded:
    "This month's projected cost of KRW {projected} exceeds this device's monthly guard of KRW {limit}.",
  backupWindowUnavailable: "The backup window is unavailable.",
  backupRestoreAndRollbackFailed:
    "Restore and automatic rollback failed. Safety backup {backupName} was preserved. {restoreError} / rollback: {rollbackError}",
  backupRestoreRolledBack: "Restore failed, so the previous data was restored automatically. {error}",
  backupRequestInvalid: "The backup request is invalid.",
  restoreRequestInvalid: "The restore request is invalid.",
  restorePreviewMissing: "The restore preview is unavailable. Review the backup file again.",
  restoreModeUnsupported: "This restore mode is not supported.",
  rendererBackupMissing: "The display-settings backup is missing.",
  rendererBackupInvalid: "The display-settings backup entries are invalid.",
  unknownError: "Unknown error",
  listeningSourceAudioFailed: "The source audio for the listening card could not be created.",
  listeningEmbeddedImportedOne: "Imported 1 embedded subtitle segment.",
  listeningEmbeddedImported: "Imported {count} embedded subtitle segments.",
  listeningEmbeddedUnavailable:
    "Text subtitles could not be imported. Run Whisper transcription if needed.",
  listeningCandidateUnavailable: "No video candidate was found.",
  listeningSegmentCreatedOne: "Created 1 sentence segment.",
  listeningSegmentsCreated: "Created {count} sentence segments.",
  listeningWhisperFailed: "Whisper subtitles could not be created.",
  listeningLocalWhisperFailed: "Whisper subtitles for the local video could not be created.",
  translationTextMissing: "Enter text to translate.",
  localVideoPlaybackFallback:
    "A playback MP4 could not be prepared. Trying the original file instead.",
  cardSyncNotConfigured: "Choose a sync folder.",
  cardSyncFolderFallback: "selected folder",
  cardSyncFolderMissing: "The sync folder “{folderName}” could not be found.",
  cardSyncRemoteFound: "A card file was found in the sync folder.",
  cardSyncFolderReady: "The sync folder is ready. It does not contain a card file yet.",
  cardSyncDisconnected: "The sync folder was disconnected.",
  cardSyncUploadedOne: "Uploaded 1 card to the sync folder.",
  cardSyncUploaded: "Uploaded {count} cards to the sync folder.",
  cardSyncDownloadedOne: "Downloaded 1 card change from the folder.",
  cardSyncDownloaded: "Downloaded {count} card changes from the folder.",
  cardSyncCompleted: "Sync complete · {uploaded} uploaded · {downloaded} downloaded",
  cardSyncConflictCopies: "Created {count} conflict copies.",
  cardSyncConflictCopyOne: "Created 1 conflict copy.",
  cardSyncFolderUnavailable: "The sync folder “{folderName}” cannot be used.",
  cardSyncRemoteMissing:
    "The sync folder does not contain a card file. Upload or run sync first.",
  cardSyncReadFailed: "The synced card file could not be read.",
  cardSyncWriteFailed: "The synced card file could not be saved safely.",
  listeningYouTubeTitle: "YouTube listening player",
  listeningYouTubePreparing: "Preparing the YouTube player…",
  listeningYouTubeError: "YouTube player error {code}",
  ocrCaptureHeading: "OCR capture",
  ocrCaptureHint: "Drag around the text you want to capture. Press Esc to cancel.",
  ocrCaptureReady: "Ctrl+Q capture ready",
  ocrAreaTooSmall: "The area is too small. Drag again.",
  ocrProcessing: "Running OCR…",
  ocrCaptureFailed: "OCR capture failed.",
  ocrDisplayUnavailable: "The display to capture could not be found.",
  ocrScreenshotUnavailable: "The screenshot could not be captured.",
  ocrWindowsOnly: "OCR currently supports only the built-in Windows OCR engine.",
  ocrComplete: "OCR is complete.",
  ocrEmpty: "No text was recognized. You can enter it directly below.",
  ocrFailed: "OCR failed. You can enter the text directly below.",
  ocrCapturedImageAlt: "Captured image",
  ocrClose: "Close",
  ocrEditableHint:
    "You can correct the OCR text. Drag an expression to save it as a reading card.",
  ocrManualCreate: "Create a reading card from the selection",
  ocrRecapture: "Capture again",
  ocrCreate: "Create reading card",
  ocrSelectFirst: "First, drag a word or expression in the OCR text.",
  ocrCreatingCard: "Creating a reading card…",
  ocrCardSaved: "The reading card was saved.",
  ocrCardSaveUnknown: "The card save result could not be confirmed.",
  ocrCardCreateFailed: "The card could not be created.",
  ocrMismatchTitle: "Check the sentence language",
  ocrProfileForcePrompt: "Save it to the current profile anyway?",
  ocrMismatchCancel: "Cancel",
  ocrMismatchSaveAnyway: "Save anyway",
  ocrMismatchSaved: "The language mismatch was acknowledged and the card was saved."
};

const catalogs: Record<ElectronAppLocale, Record<ElectronTextKey, string>> = { ko, en };

export function normalizeElectronAppLocale(value: unknown): ElectronAppLocale {
  return typeof value === "string" && value.toLowerCase().startsWith("en") ? "en" : "ko";
}

export function electronText(locale: ElectronAppLocale, key: ElectronTextKey) {
  return catalogs[locale][key];
}

export function formatElectronText(
  locale: ElectronAppLocale,
  key: ElectronTextKey,
  replacements: Readonly<Record<string, string | number>>
) {
  return electronText(locale, key).replace(/\{([A-Za-z][A-Za-z0-9]*)\}/g, (match, name: string) =>
    Object.prototype.hasOwnProperty.call(replacements, name)
      ? String(replacements[name])
      : match
  );
}

export function formatElectronNumber(locale: ElectronAppLocale, value: number) {
  return new Intl.NumberFormat(locale === "en" ? "en-US" : "ko-KR").format(value);
}
